version: 1.0.{build}
image: Visual Studio 2015
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
configuration: Release
platform: Any CPU
init:
- ps: >-
    if ($env:APPVEYOR_REPO_BRANCH -ne "master") {
       Update-AppveyorBuild -Version "${env:APPVEYOR_BUILD_VERSION}-alpha"
    }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore .\Src\Jobbie.sln
build:
  project: .\Src\Jobbie.sln
  publish_nuget: true
  include_nuget_references: true
after_test:
- ps: >-
    . $env:USERPROFILE\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe `
        -register:user `
        -filter:"+[Jobbie.Domain]* +[Jobbie.Infrastructure]* +[Jobbie.Executor]*" `
        -target:"$env:USERPROFILE\.nuget\packages\NUnit.ConsoleRunner\3.6.1\tools\nunit3-console.exe" `
        -targetargs:".\Src\Jobbie.Domain.Tests.Unit\bin\$env:CONFIGURATION\Jobbie.Domain.Tests.Unit.dll .\Src\Jobbie.Infrastructure.Tests.Unit\bin\$env:CONFIGURATION\Jobbie.Infrastructure.Tests.Unit.dll .\Src\Jobbie.Executor.Tests.Unit\bin\$env:CONFIGURATION\Jobbie.Executor.Tests.Unit.dll .\Src\Jobbie.Scheduler.Tests.Unit\bin\$env:CONFIGURATION\Jobbie.Scheduler.Tests.Unit.dll" `
        -output:Coverage.xml

    . $env:USERPROFILE\.nuget\packages\coveralls.io\1.3.4\tools\coveralls.net.exe `
        --opencover Coverage.xml `
        --repo-token vWxX8vfvSkE2iMrfNVUmcnP4NPDnvtBES
deploy: off
