version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore .\Src\Jobbie.sln
build:
  project: .\Src\Jobbie.sln
after_test:
- ps: >-
    . $env:USERPROFILE\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe `
        -register:user `
        -filter:"+[Jobbie.Domain]*" `
        -target:"$env:USERPROFILE\.nuget\packages\NUnit.ConsoleRunner\3.6.1\tools\nunit3-console.exe" `
        -targetargs:".\Src\Jobbie.Domain.Tests.Unit\bin\$env:CONFIGURATION\Jobbie.Domain.Tests.Unit.dll" `
        -output:Coverage.xml

    . $env:USERPROFILE\.nuget\packages\coveralls.io\1.3.4\tools\coveralls.net.exe `
        --opencover Coverage.xml `
        --repo-token vWxX8vfvSkE2iMrfNVUmcnP4NPDnvtBES
deploy: off
